[tool.poetry]
name = "ams-brief"
version = "0.1.65"
description = ""
authors = ["Lucas <lucas@animotions.be>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
fpdf = "^1.7.2"
imagesize = "^1.3.0"
pick = "^1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ams-brief = "ams_brief.console:main"