[tool.poetry]
name = "pywebcanvas"
version = "0.2.1.dev0"
description = ""
authors = ["Isaac Beverly"]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
colour = "^0.1.5"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]
httpserver = "^1.1.0"

[tool.poetry.scripts]
pywebcanvas = "pywebcanvas.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
