[tool.poetry]
# https://python-poetry.org/docs/pyproject/
# https://github.com/python-poetry/poetry/blob/master/pyproject.toml
name = "qary"
version = "0.7.14"
description = "A chatbot that assists rather than manipulates."
license = "GPLv3"
readme = "README.md"
authors = [
    "Hobson Lane <hobson@tangibleai.com>",
    "Maria Dyshel <maria@tangibleai.com>",
    "Leo Hepis <leo@leohepis.com>",
    "Geoffrey Marshal",
    "Sylvia Lee",
    "Winnie Yeung @dcvionwinnie",
    "Mohammed Dala Ali <mms.dala@gmail.com>",
    "Alex Rosengarten @alxrsngrtn",
    "Jose Robins @jorobins",
    ]
homepage = "https://gitlab.com/tangibleai/qary"
repository = "https://gitlab.com/tangibleai/qary"
documentation = "https://docs.qary.ai"
include = [
    "src/qary/data/datasets.yml",
    "src/qary/data/constants/nltk_stopwords_english.json",
    "src/qary/data/*",
    "src/qary/data/constants/*",
    ]

# https://python-poetry.org/docs/pyproject/#keywords
keywords = ['NLP', 'Natural Language Processing', 'Virtual Assistant', 'chatbot', 'Text Processing', 'Machine Learning', 'Text Mining', 'Deep Learning']
# https://pypi.org/classifiers/
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Text Processing :: Linguistic",
  "Topic :: Text Processing",
  "Topic :: Communications",
  "Topic :: Communications :: Chat",
  "Intended Audience :: Education",
]

[tool.poetry.build]
generate-setup-file = true

# [build-system]
# requires = ["poetry_core>=1.0.0", "setuptools>=54.0.2", "tox", "wheel"]
# build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
# https://python-poetry.org/docs/pyproject/#scripts
"qary" = "qary.clibot:main"

[tool.poetry.dependencies]
python = "^3.8.3,<3.10.0"
poetry = ">=1.1.13"

beautifulsoup4 = "4.11.1"
bidict = "^0.22"
boto3 = "1.22.2"
botocore = "1.25.3"
ConfigArgParse = "1.5.3"
Cython = ">=0.29.28"
# datasets = "^1"
django = "^4.0"
# docutils = "0.18.1"
edit-distance = "1.0.4"
elasticsearch = "7.17.3"
environment = "1.0.0"
gitpython = "^3.1.27"
graphviz = "^0.20"
# graphviz = "^2.48.0"
h5py = "^3.6.0"
html5lib = "1.1"
html2text = "^2020.1.16"
jedi = "0.18.1"
jupyter = "1.0.0"
jupyter-client = ">=7.3.0"
# jupyter-core = "^4.0.0"
jupyter-console = ">=6.4.2"
lxml = "4.6.3"
m2r = "0.2.1"  # [required by Sphinx & m2r](https://github.com/CrossNox/m2r2/issues/40)
matplotlib = "3.5.1"
matplotlib-inline = "0.1.3"
meilisearch = "0.18.2"
mistune = "0.8.4"
nessvec = "^0.0"
# nessvec.git = "https://gitlab.com/tangibleai/nessvec.git"
# nessvec.rev = "a926dff"
# # nessvec.tag = "0.0.13rc1"
# # nessvec.branch = "main"
pandas = "1.1.3"
pillow = "9.1.0"
pip = "^22.0"
pronouncing = "0.2.0"
psutil = "^5.8.0"
python-dotenv = "^0.13.0"
python-slugify = "4.0.0"
pyyaml = "6.0"
rapidfuzz = "0.9.1"
# readability = "^0.3.1"
recommonmark = "0.6.0"
# regex = "^2022.4.24"
scikit-image = "^0.17.2"
scikit-learn = "^1.0"
scipy = "1.8.0"
seaborn = "^0.11.2"
sentence_transformers = "^2.2.0"
spacy = "3.2.4"
torch = "1.11.0"
# torchtext = "0.12.0"
# torchvision = "0.12.0"
tox = "^3.25.0"
tqdm = "^4.60.0"
# transformers = "4.11.3"  # ">=4.18.0"
# typer = "^0.4.1"
wikipedia = "^1.4"
# nlpia_wikipedia = "^1.4"

[tool.poetry.dev-dependencies]
tox = "^3.18"
pytest = ">=6.2.0"
pytest-cov = "^3.0.0"
# pytest-mock = "^3.5"
# pytest-sugar = "^0.9"
pylint = "^2.6.0"
pre-commit = "^2.6"
deepdiff = "^5.0"
httpretty = "^1.0"
typing-extensions = { version = "^4.0.0", python = "<3.8" }
zipp = { version = "^3.4", python = "<3.8" }
flatdict = "^4.0.1"
pydocstyle = "^5.1.1"
Sphinx = "^4.4.0"

[tool.black]
# https://github.com/psf/black
line-length = 80
target-version = ["py37"]

[tool.isort]
# https://github.com/timothycrosley/isort/
py_version = 37
profile = "black"
force_single_line = true
combine_as_imports = true
lines_between_types = 1
lines_after_imports = 2
src_paths = ["src", "tests"]
extend_skip = ["setup.py"]
known_typing = "typing,types,typing_extensions,mypy,mypy_extensions"
sections = "FUTURE,TYPING,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
include_trailing_comma = true
line_length = 80
indent = 4
use_parentheses = true
