[tool.poetry]
name = "my_mltools"
version = "0.3.1"
description = "My machine learning toolkit."
authors = ["Yang Wu"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
scikit-learn = "^1.0.2"
pandas = "^1.4.2"
kneed = "^0.7.0"
yellowbrick = "^1.4"
tensorflow = "^2.8.0"

[tool.poetry.dev-dependencies]
pytest-plt = "^1.1.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
python-semantic-release = "^7.28.1"

[tool.semantic_release]
version_variable = "pyproject.toml:version" # version location
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
build_command = "poetry build"              # build dists
dist_path = "dist/"                         # where to put dists
upload_to_release = true                    # auto-create GitHub release
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
patch_without_tag = false                   # don't patch release by default

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
