[tool.poetry]
name = "audit-tools"
version = "0.1.12"
description = "Auditing tools for Cova POS files"
readme = "README.md"
repository = "https://github.com/JakePIXL/audit-tools"
authors = ["JakePIXL <jakewjevans@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.2"
numpy = "^1.22.3"
rich = "^12.2.0"
pydantic = "^1.9.0"
openpyxl = "^3.0.9"

[tool.poetry.dev-dependencies]
pytest = "^6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
